<?php
/**
 * @file
 * Code for the List options support
 */

/**
 * Implements hook_form_alter().
 */
function list_text_support_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'field_ui_field_edit_form') {
    if ($form['#field']['module'] == 'list') {
      list_text_support_add_options($form['field']['settings']);
    }
  } elseif ($form_id == 'field_ui_field_settings_form') {
    if ($form['field']['module']['#value'] == 'list') {
      list_text_support_add_options($form['field']['settings']);
    }
  }
}

function list_text_support_add_options(&$field_settings) {
  $field_settings['allowed_values_function'] = array(
    '#type' => 'select',
    '#title' => t('Allowed values'),
    '#options' => list_text_support_get_callback_options() + array('' => t('Custom')),
    '#default_value' => $field_settings['allowed_values_function']['#value'],
    '#weight' => -10,
  );
  $field_settings['allowed_values']['#states']['visible'][':input[name="field[settings][allowed_values_function]"]'] = array('value' => '');
  $field_settings['allowed_values']['#access'] = TRUE;
  $field_settings['allowed_values_function_display']['#access'] = FALSE;
}

/**
 * Get all the predefined options via hook_list_option_info().
 *
 * @see hook_list_option_info()
 * @see hook_list_option_info_alter()
 */
function list_text_support_get_list_option_info() {
  $info = &drupal_static(__FUNCTION__);
  if (!isset($options)) {
    $cid = "list:predefined-option:info:" . $GLOBALS['language']->language;
    if ($cache = cache_get($cid)) {
      $info = $cache->data;
    }
    else {
      $info = module_invoke_all('list_option_info');
      drupal_alter('list_option_info', $info);
      cache_set($cid, $info);
    }
  }
  return $info;
}

/**
 * Get an array of predefined options prepared for #options.
 *
 * The array will be formatted with the option callback as the keys, and the
 * label as the values.
 */
function list_text_support_get_callback_options() {
  $info = list_text_support_get_list_option_info();
  $options = array();
  foreach ($info as $option) {
    $options[$option['callback']] = $option['label'];
  }
  return $options;
}

/**
 * Implements hook_list_option_info().
 */
function list_text_support_list_option_info() {
  $info['image_style'] = array(
    'label' => t('Image Styles'),
    'callback' => 'list_text_support_list_option_image_styles',
  );
  $info['content_type'] = array(
    'label' => t('Content Types'),
    'callback' => 'list_text_support_list_option_content_type',
  );
  $info['user_roles'] = array(
    'label' => t('User Roles'),
    'callback' => 'list_text_support_list_option_user_roles',
  );
  return $info;
}


/**
 * List option callback for image style
 */
function list_text_support_list_option_image_styles() {
  $image_styles = image_styles();
  $options = array();
  if($image_styles) {
    foreach ($image_styles as $key => $value) {
      $options[$key] = $key;
    }
  }
  return $options;
}

/**
 * List option callback for content types
 */
function list_text_support_list_option_content_type() {
  $content_types = node_type_get_types();
  $options = array();
  if($content_types) {
    foreach ($content_types as $key => $value) {
      $options[$key] = $value->name;
    }
  }
  return $options;
}

/**
 * List option callback for user roles
 */
function list_text_support_list_option_user_roles() {
  $user_roles = user_roles();
  $options = array();
  if($user_roles) {
    foreach ($user_roles as $key => $value) {
      $options[$value] = $value;
    }
  }
  return $options;
}

